// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5tKBaLo87jlbyiZRJP1soc3au5Fztek4',
    appId: '1:188640590513:web:d3c816ecc85bf2cc614090',
    messagingSenderId: '188640590513',
    projectId: 'toptanuygulamam',
    authDomain: 'toptanuygulamam.firebaseapp.com',
    storageBucket: 'toptanuygulamam.firebasestorage.app',
    measurementId: 'G-8N3VYJQYPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTu8oygo-iY5Hw0NCkpu5AJmkLOwDgMHg',
    appId: '1:188640590513:android:19976b2ad53db818614090',
    messagingSenderId: '188640590513',
    projectId: 'toptanuygulamam',
    storageBucket: 'toptanuygulamam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk5cLLw3QIPMcmEZGoT92FxWUH4El5zMs',
    appId: '1:188640590513:ios:f38490fb9499844b614090',
    messagingSenderId: '188640590513',
    projectId: 'toptanuygulamam',
    storageBucket: 'toptanuygulamam.firebasestorage.app',
    iosBundleId: 'com.example.toptansatis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk5cLLw3QIPMcmEZGoT92FxWUH4El5zMs',
    appId: '1:188640590513:ios:f38490fb9499844b614090',
    messagingSenderId: '188640590513',
    projectId: 'toptanuygulamam',
    storageBucket: 'toptanuygulamam.firebasestorage.app',
    iosBundleId: 'com.example.toptansatis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5tKBaLo87jlbyiZRJP1soc3au5Fztek4',
    appId: '1:188640590513:web:0b52a7d7911e3dd7614090',
    messagingSenderId: '188640590513',
    projectId: 'toptanuygulamam',
    authDomain: 'toptanuygulamam.firebaseapp.com',
    storageBucket: 'toptanuygulamam.firebasestorage.app',
    measurementId: 'G-PY7MPMLPYE',
  );
}
